name: 4.3$(rev:.r)
trigger:
  branches:
    include:
      - master
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    displayName: Install Bun
    inputs:
      targetType: 'inline'
      script: |
        curl -fsSL https://bun.sh/install | bash
        echo "##vso[task.prependpath]$HOME/.bun/bin"

  # Authenticate
  - task: npmAuthenticate@0
    displayName: Registry Auth
    inputs:
      workingFile: .npmrc
      customEndpoint: 'NPM(Vishnu Sankar)'

  # Set Version
  - task: Bash@3
    displayName: 'Set Version'
    inputs:
      targetType: 'inline'
      script: 'bun ./scripts/set-workspace-version.ts "$BUILD_BUILDNUMBER"'
      # failOnStderr: true

  # Install
  - task: Bash@3
    displayName: 'Install'
    inputs:
      targetType: 'inline'
      script: 'bun install --frozen-lockfile'

  # Test
  - task: Bash@3
    displayName: 'Test'
    inputs:
      targetType: 'inline'
      script: 'bun run test:ci'

  # Build
  - task: Bash@3
    displayName: 'Build'
    inputs:
      targetType: 'inline'
      script: |
        bun --cwd packages/next-sitemap run build
        bun --cwd packages/next-sitemap run postbuild

  # Copy README
  - task: Bash@3
    displayName: 'Copy README'
    inputs:
      targetType: 'inline'
      script: 'cp README.md packages/next-sitemap/README.md'
      failOnStderr: true

  # Test Result
  - task: PublishTestResults@2
    displayName: Publish Test Result
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit.xml'
      failTaskOnFailedTests: true

  # Publish Packages
  - task: Bash@3
    displayName: 'Publish Packages'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      targetType: 'inline'
      script: 'bun publish --cwd packages/next-sitemap --access public'
      # failOnStderr: true

  # Github Release
  - task: GitHubRelease@1
    displayName: Github Release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      gitHubConnection: 'iamvishnusankar'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'v$(Build.BuildNumber)'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
